apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  2;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
       map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
       }

      server {
          listen       8080;
          server_name  localhost;

          location ~ ^/static/js/(.*).min.js.* {
            resolver kube-dns.kube-system.svc.cluster.local;
            return 301 https://cdn.bokeh.org/bokeh/release/$1-3.3.1.min.js;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 86400;
          }

          # location ~ ^/static/.* {
          #   resolver kube-dns.kube-system.svc.cluster.local;
          #   proxy_pass http://dask-ivukotic-c9caa1e2-b.af-jupyter.svc.cluster.local:8787;  
            
          #   proxy_set_header Host $http_host;
          #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          #   proxy_set_header X-Real-IP $remote_addr;
          #   proxy_http_version 1.1;
          #   proxy_redirect off;
          #   proxy_buffering off;
          #   proxy_set_header Upgrade $http_upgrade;
          #   proxy_set_header Connection $connection_upgrade;
          #   proxy_read_timeout 86400;
          # }
          
          location ~ ^/(.*).af-jupyter/(.*) {

            add_header X-debug-message-1 "Matched Initial URL" always;
            resolver kube-dns.kube-system.svc.cluster.local;

            set $svcname $1;
            set $match2 $2;

            rewrite /dask-.*-jupyter/(.*) /$1 break;
            add_header X-debug-message-2 "rewrote URL to $request_uri $svcname /$1" always;
            proxy_pass http://$svcname.af-jupyter.svc.cluster.local:8787;  

            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 86400;
          }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n4dask
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx # mount nginx-conf volume to /etc/nginx
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
