name: Build AnalysisBase ML image
on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  repository_dispatch:
    types: gitops-analysis-base-trigger
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            sslhep/analysis-dask-uc
            hub.opensciencegrid.org/usatlas/analysis-dask-uc           
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha   

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
      - name: Login to Harbor Container Registry
        uses: docker/login-action@v3
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          push: true          
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    #   - name: Repository Dispatch
    #     uses: peter-evans/repository-dispatch@v2.1.2
    #     with:
    #       token: ${{ secrets.GITOPS_REBUILD_TRIGGER }}
    #       repository: analysis-dask/usatlas
    #       event-type: gitops-analysis-base-trigger
    #       client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


    #   - name: Update Version In Checked-Out Code
    #     if: ${{ github.event.client_payload.sha }}
    #     run: |
    #       sed -i "s@\(.*image:\).*@\1 docker.io/sandci/alarms_and_alerts:${{ github.event.client_payload.sha }}@" ${GITHUB_WORKSPACE}/atlas-analytics/crons/perfsonar/*.yaml
    #   - name: Commit The New Image Reference
    #     uses: stefanzweifel/git-auto-commit-action@v4.16.0
    #     if: ${{ github.event.client_payload.sha }}
    #     with:
    #       commit_message: Deploy new AAAS PerfSONAR image ${{ github.event.client_payload.sha }}
    #       branch: main
    #       commit_options: "--no-verify --signoff"
    #       repository: .
    #       commit_user_name: AAAS GitOps Bot
    #       commit_user_email: ilijav@gmail.com
    #       commit_author: AAAS GitOps Bot <ilijav@gmail.com>
