name: Build AnalysisBase ML image
on:
  push:
    branches:
      - "main"
  repository_dispatch:
    types: gitops-analysis-base-trigger
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: sslhep/analysis-dask-uc:latest, sslhep/analysis-dask-uc:${{ github.sha }}

    #   - name: Repository Dispatch
    #     uses: peter-evans/repository-dispatch@v2.1.2
    #     with:
    #       token: ${{ secrets.GITOPS_REBUILD_TRIGGER }}
    #       repository: analysis-dask/usatlas
    #       event-type: gitops-analysis-base-trigger
    #       client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


    #   - name: Update Version In Checked-Out Code
    #     if: ${{ github.event.client_payload.sha }}
    #     run: |
    #       sed -i "s@\(.*image:\).*@\1 docker.io/sandci/alarms_and_alerts:${{ github.event.client_payload.sha }}@" ${GITHUB_WORKSPACE}/atlas-analytics/crons/perfsonar/*.yaml
    #   - name: Commit The New Image Reference
    #     uses: stefanzweifel/git-auto-commit-action@v4.16.0
    #     if: ${{ github.event.client_payload.sha }}
    #     with:
    #       commit_message: Deploy new AAAS PerfSONAR image ${{ github.event.client_payload.sha }}
    #       branch: main
    #       commit_options: "--no-verify --signoff"
    #       repository: .
    #       commit_user_name: AAAS GitOps Bot
    #       commit_user_email: ilijav@gmail.com
    #       commit_author: AAAS GitOps Bot <ilijav@gmail.com>
